name: Deploy to GCP Cloud Run

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - develop

env:
  GCP_PROJECT_ID: correlator-453922
  GCP_REGION: us-west1
  CR_NAMESPACE: correlator
  IMAGE_NAME: correlator
  TAG: latest
  SERVICE_NAME: correlator

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure Docker for GCP
        run: |
          gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }} .
          docker tag ${{ env.IMAGE_NAME }}:${{ env.TAG }} ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.CR_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

      - name: Push Docker image to GCP
        run: |
          docker push ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.CR_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

      - name: Deploy to Cloud Run
        run: |
          if [ "${{ github.ref }}" == "refs/heads/master" ]; then
            SERVICE_NAME=${{ env.SERVICE_NAME }}
          else
            SERVICE_NAME=${{ env.SERVICE_NAME }}-dev
          fi

          gcloud run deploy $SERVICE_NAME \
            --image ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.CR_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} \
            --platform managed \
            --region ${{ env.GCP_REGION }} \
            --allow-unauthenticated \
            --port 8080 \
            --memory 2Gi \
            --cpu 4 \
            --min-instances 1
